import { Component, OnInit } from '@angular/core';
import { DEFAULT_NGX_ACE_OPTIONS } from '@nowzoo/ngx-ace';
@Component({
  selector: 'app-demo',
  templateUrl: './demo.component.html',
  styleUrls: ['./demo.component.scss']
})
export class DemoComponent implements OnInit {

  content = 'Hello World';
  themes = DEFAULT_NGX_ACE_OPTIONS.themes;
  theme = 'chrome';
  fontSizes = ['8px', '10px', '14px', '16px', '18px', '20px'];
  fontSize = '16px';

  modes = [
    {id: 'abap', label: 'ABAP'},
    {id: 'abc', label: 'ABC'},
    {id: 'actionscript', label: 'ActionScript'},
    {id: 'ada', label: 'ADA'},
    {id: 'apache_conf', label: 'Apache Conf'},
    {id: 'asciidoc', label: 'AsciiDoc'},
    {id: 'asl', label: 'ASL'},
    {id: 'assembly_x86', label: 'Assembly x86'},
    {id: 'autohotkey', label: 'AutoHotKey'},
    {id: 'apex', label: 'Apex'},
    {id: 'batchfile', label: 'BatchFile'},
    {id: 'bro', label: 'Bro'},
    {id: 'c_cpp', label: 'C and C++'},
    {id: 'c9search', label: 'C9Search'},
    {id: 'cirru', label: 'Cirru'},
    {id: 'clojure', label: 'Clojure'},
    {id: 'cobol', label: 'Cobol'},
    {id: 'coffee', label: 'CoffeeScript'},
    {id: 'coldfusion', label: 'ColdFusion'},
    {id: 'csharp', label: 'C#'},
    {id: 'csound_document', label: 'Csound Document'},
    {id: 'csound_orchestra', label: 'Csound'},
    {id: 'csound_score', label: 'Csound Score'},
    {id: 'css', label: 'CSS'},
    {id: 'curly', label: 'Curly'},
    {id: 'd', label: 'D'},
    {id: 'dart', label: 'Dart'},
    {id: 'diff', label: 'Diff'},
    {id: 'dockerfile', label: 'Dockerfile'},
    {id: 'dot', label: 'Dot'},
    {id: 'drools', label: 'Drools'},
    {id: 'edifact', label: 'Edifact'},
    {id: 'eiffel', label: 'Eiffel'},
    {id: 'ejs', label: 'EJS'},
    {id: 'elixir', label: 'Elixir'},
    {id: 'elm', label: 'Elm'},
    {id: 'erlang', label: 'Erlang'},
    {id: 'forth', label: 'Forth'},
    {id: 'fortran', label: 'Fortran'},
    {id: 'fsharp', label: 'FSharp'},
    {id: 'fsl', label: 'FSL'},
    {id: 'ftl', label: 'FreeMarker'},
    {id: 'gcode', label: 'Gcode'},
    {id: 'gherkin', label: 'Gherkin'},
    {id: 'gitignore', label: 'Gitignore'},
    {id: 'glsl', label: 'Glsl'},
    {id: 'gobstones', label: 'Gobstones'},
    {id: 'golang', label: 'Go'},
    {id: 'graphqlschema', label: 'GraphQLSchema'},
    {id: 'groovy', label: 'Groovy'},
    {id: 'haml', label: 'HAML'},
    {id: 'handlebars', label: 'Handlebars'},
    {id: 'haskell', label: 'Haskell'},
    {id: 'haskell_cabal', label: 'Haskell Cabal'},
    {id: 'haxe', label: 'haXe'},
    {id: 'hjson', label: 'Hjson'},
    {id: 'html', label: 'HTML'},
    {id: 'html_elixir', label: 'HTML (Elixir)'},
    {id: 'html_ruby', label: 'HTML (Ruby)'},
    {id: 'ini', label: 'INI'},
    {id: 'io', label: 'Io'},
    {id: 'jack', label: 'Jack'},
    {id: 'jade', label: 'Jade'},
    {id: 'java', label: 'Java'},
    {id: 'javascript', label: 'JavaScript'},
    {id: 'json', label: 'JSON'},
    {id: 'jsoniq', label: 'JSONiq'},
    {id: 'jsp', label: 'JSP'},
    {id: 'jssm', label: 'JSSM'},
    {id: 'jsx', label: 'JSX'},
    {id: 'julia', label: 'Julia'},
    {id: 'kotlin', label: 'Kotlin'},
    {id: 'latex', label: 'LaTeX'},
    {id: 'less', label: 'LESS'},
    {id: 'liquid', label: 'Liquid'},
    {id: 'lisp', label: 'Lisp'},
    {id: 'livescript', label: 'LiveScript'},
    {id: 'logiql', label: 'LogiQL'},
    {id: 'lsl', label: 'LSL'},
    {id: 'lua', label: 'Lua'},
    {id: 'luapage', label: 'LuaPage'},
    {id: 'lucene', label: 'Lucene'},
    {id: 'makefile', label: 'Makefile'},
    {id: 'markdown', label: 'Markdown'},
    {id: 'mask', label: 'Mask'},
    {id: 'matlab', label: 'MATLAB'},
    {id: 'maze', label: 'Maze'},
    {id: 'mel', label: 'MEL'},
    {id: 'mixal', label: 'MIXAL'},
    {id: 'mushcode', label: 'MUSHCode'},
    {id: 'mysql', label: 'MySQL'},
    {id: 'nix', label: 'Nix'},
    {id: 'nsis', label: 'NSIS'},
    {id: 'objectivec', label: 'Objective-C'},
    {id: 'ocaml', label: 'OCaml'},
    {id: 'pascal', label: 'Pascal'},
    {id: 'perl', label: 'Perl'},
    {id: 'perl6', label: 'Perl 6'},
    {id: 'pgsql', label: 'pgSQL'},
    {id: 'php_laravel_blade', label: 'PHP (Blade Template)'},
    {id: 'php', label: 'PHP'},
    {id: 'puppet', label: 'Puppet'},
    {id: 'pig', label: 'Pig'},
    {id: 'powershell', label: 'Powershell'},
    {id: 'praat', label: 'Praat'},
    {id: 'prolog', label: 'Prolog'},
    {id: 'properties', label: 'Properties'},
    {id: 'protobuf', label: 'Protobuf'},
    {id: 'python', label: 'Python'},
    {id: 'r', label: 'R'},
    {id: 'razor', label: 'Razor'},
    {id: 'rdoc', label: 'RDoc'},
    {id: 'red', label: 'Red'},
    {id: 'rhtml', label: 'RHTML'},
    {id: 'rst', label: 'RST'},
    {id: 'ruby', label: 'Ruby'},
    {id: 'rust', label: 'Rust'},
    {id: 'sass', label: 'SASS'},
    {id: 'scad', label: 'SCAD'},
    {id: 'scala', label: 'Scala'},
    {id: 'scheme', label: 'Scheme'},
    {id: 'scss', label: 'SCSS'},
    {id: 'sh', label: 'SH'},
    {id: 'sjs', label: 'SJS'},
    {id: 'slim', label: 'Slim'},
    {id: 'smarty', label: 'Smarty'},
    {id: 'snippets', label: 'snippets'},
    {id: 'soy_template', label: 'Soy Template'},
    {id: 'space', label: 'Space'},
    {id: 'sql', label: 'SQL'},
    {id: 'sqlserver', label: 'SQLServer'},
    {id: 'stylus', label: 'Stylus'},
    {id: 'svg', label: 'SVG'},
    {id: 'swift', label: 'Swift'},
    {id: 'tcl', label: 'Tcl'},
    {id: 'terraform', label: 'Terraform'},
    {id: 'tex', label: 'Tex'},
    {id: 'text', label: 'Text'},
    {id: 'textile', label: 'Textile'},
    {id: 'toml', label: 'Toml'},
    {id: 'tsx', label: 'TSX'},
    {id: 'twig', label: 'Twig'},
    {id: 'typescript', label: 'Typescript'},
    {id: 'vala', label: 'Vala'},
    {id: 'vbscript', label: 'VBScript'},
    {id: 'velocity', label: 'Velocity'},
    {id: 'verilog', label: 'Verilog'},
    {id: 'vhdl', label: 'VHDL'},
    {id: 'visualforce', label: 'Visualforce'},
    {id: 'wollok', label: 'Wollok'},
    {id: 'xml', label: 'XML'},
    {id: 'xquery', label: 'XQuery'},
    {id: 'yaml', label: 'YAML'},
    {id: 'django', label: 'Django'},
  ];
  mode = 'markdown';
  constructor() { }

  ngOnInit() {
  }

}
