export const MODES = [
  {id: 'ace/mode/abap', label: 'ABAP'},
  {id: 'ace/mode/abc', label: 'ABC'},
  {id: 'ace/mode/actionscript', label: 'ActionScript'},
  {id: 'ace/mode/ada', label: 'ADA'},
  {id: 'ace/mode/apache_conf', label: 'Apache Conf'},
  {id: 'ace/mode/asciidoc', label: 'AsciiDoc'},
  {id: 'ace/mode/asl', label: 'ASL'},
  {id: 'ace/mode/assembly_x86', label: 'Assembly x86'},
  {id: 'ace/mode/autohotkey', label: 'AutoHotKey'},
  {id: 'ace/mode/apex', label: 'Apex'},
  {id: 'ace/mode/batchfile', label: 'BatchFile'},
  {id: 'ace/mode/bro', label: 'Bro'},
  {id: 'ace/mode/c_cpp', label: 'C and C++'},
  {id: 'ace/mode/c9search', label: 'C9Search'},
  {id: 'ace/mode/cirru', label: 'Cirru'},
  {id: 'ace/mode/clojure', label: 'Clojure'},
  {id: 'ace/mode/cobol', label: 'Cobol'},
  {id: 'ace/mode/coffee', label: 'CoffeeScript'},
  {id: 'ace/mode/coldfusion', label: 'ColdFusion'},
  {id: 'ace/mode/csharp', label: 'C#'},
  {id: 'ace/mode/csound_document', label: 'Csound Document'},
  {id: 'ace/mode/csound_orchestra', label: 'Csound'},
  {id: 'ace/mode/csound_score', label: 'Csound Score'},
  {id: 'ace/mode/css', label: 'CSS'},
  {id: 'ace/mode/curly', label: 'Curly'},
  {id: 'ace/mode/d', label: 'D'},
  {id: 'ace/mode/dart', label: 'Dart'},
  {id: 'ace/mode/diff', label: 'Diff'},
  {id: 'ace/mode/dockerfile', label: 'Dockerfile'},
  {id: 'ace/mode/dot', label: 'Dot'},
  {id: 'ace/mode/drools', label: 'Drools'},
  {id: 'ace/mode/edifact', label: 'Edifact'},
  {id: 'ace/mode/eiffel', label: 'Eiffel'},
  {id: 'ace/mode/ejs', label: 'EJS'},
  {id: 'ace/mode/elixir', label: 'Elixir'},
  {id: 'ace/mode/elm', label: 'Elm'},
  {id: 'ace/mode/erlang', label: 'Erlang'},
  {id: 'ace/mode/forth', label: 'Forth'},
  {id: 'ace/mode/fortran', label: 'Fortran'},
  {id: 'ace/mode/fsharp', label: 'FSharp'},
  {id: 'ace/mode/fsl', label: 'FSL'},
  {id: 'ace/mode/ftl', label: 'FreeMarker'},
  {id: 'ace/mode/gcode', label: 'Gcode'},
  {id: 'ace/mode/gherkin', label: 'Gherkin'},
  {id: 'ace/mode/gitignore', label: 'Gitignore'},
  {id: 'ace/mode/glsl', label: 'Glsl'},
  {id: 'ace/mode/gobstones', label: 'Gobstones'},
  {id: 'ace/mode/golang', label: 'Go'},
  {id: 'ace/mode/graphqlschema', label: 'GraphQLSchema'},
  {id: 'ace/mode/groovy', label: 'Groovy'},
  {id: 'ace/mode/haml', label: 'HAML'},
  {id: 'ace/mode/handlebars', label: 'Handlebars'},
  {id: 'ace/mode/haskell', label: 'Haskell'},
  {id: 'ace/mode/haskell_cabal', label: 'Haskell Cabal'},
  {id: 'ace/mode/haxe', label: 'haXe'},
  {id: 'ace/mode/hjson', label: 'Hjson'},
  {id: 'ace/mode/html', label: 'HTML'},
  {id: 'ace/mode/html_elixir', label: 'HTML (Elixir)'},
  {id: 'ace/mode/html_ruby', label: 'HTML (Ruby)'},
  {id: 'ace/mode/ini', label: 'INI'},
  {id: 'ace/mode/io', label: 'Io'},
  {id: 'ace/mode/jack', label: 'Jack'},
  {id: 'ace/mode/jade', label: 'Jade'},
  {id: 'ace/mode/java', label: 'Java'},
  {id: 'ace/mode/javascript', label: 'JavaScript'},
  {id: 'ace/mode/json', label: 'JSON'},
  {id: 'ace/mode/jsoniq', label: 'JSONiq'},
  {id: 'ace/mode/jsp', label: 'JSP'},
  {id: 'ace/mode/jssm', label: 'JSSM'},
  {id: 'ace/mode/jsx', label: 'JSX'},
  {id: 'ace/mode/julia', label: 'Julia'},
  {id: 'ace/mode/kotlin', label: 'Kotlin'},
  {id: 'ace/mode/latex', label: 'LaTeX'},
  {id: 'ace/mode/less', label: 'LESS'},
  {id: 'ace/mode/liquid', label: 'Liquid'},
  {id: 'ace/mode/lisp', label: 'Lisp'},
  {id: 'ace/mode/livescript', label: 'LiveScript'},
  {id: 'ace/mode/logiql', label: 'LogiQL'},
  {id: 'ace/mode/lsl', label: 'LSL'},
  {id: 'ace/mode/lua', label: 'Lua'},
  {id: 'ace/mode/luapage', label: 'LuaPage'},
  {id: 'ace/mode/lucene', label: 'Lucene'},
  {id: 'ace/mode/makefile', label: 'Makefile'},
  {id: 'ace/mode/markdown', label: 'Markdown'},
  {id: 'ace/mode/mask', label: 'Mask'},
  {id: 'ace/mode/matlab', label: 'MATLAB'},
  {id: 'ace/mode/maze', label: 'Maze'},
  {id: 'ace/mode/mel', label: 'MEL'},
  {id: 'ace/mode/mixal', label: 'MIXAL'},
  {id: 'ace/mode/mushcode', label: 'MUSHCode'},
  {id: 'ace/mode/mysql', label: 'MySQL'},
  {id: 'ace/mode/nix', label: 'Nix'},
  {id: 'ace/mode/nsis', label: 'NSIS'},
  {id: 'ace/mode/objectivec', label: 'Objective-C'},
  {id: 'ace/mode/ocaml', label: 'OCaml'},
  {id: 'ace/mode/pascal', label: 'Pascal'},
  {id: 'ace/mode/perl', label: 'Perl'},
  {id: 'ace/mode/perl6', label: 'Perl 6'},
  {id: 'ace/mode/pgsql', label: 'pgSQL'},
  {id: 'ace/mode/php_laravel_blade', label: 'PHP (Blade Template)'},
  {id: 'ace/mode/php', label: 'PHP'},
  {id: 'ace/mode/puppet', label: 'Puppet'},
  {id: 'ace/mode/pig', label: 'Pig'},
  {id: 'ace/mode/powershell', label: 'Powershell'},
  {id: 'ace/mode/praat', label: 'Praat'},
  {id: 'ace/mode/prolog', label: 'Prolog'},
  {id: 'ace/mode/properties', label: 'Properties'},
  {id: 'ace/mode/protobuf', label: 'Protobuf'},
  {id: 'ace/mode/python', label: 'Python'},
  {id: 'ace/mode/r', label: 'R'},
  {id: 'ace/mode/razor', label: 'Razor'},
  {id: 'ace/mode/rdoc', label: 'RDoc'},
  {id: 'ace/mode/red', label: 'Red'},
  {id: 'ace/mode/rhtml', label: 'RHTML'},
  {id: 'ace/mode/rst', label: 'RST'},
  {id: 'ace/mode/ruby', label: 'Ruby'},
  {id: 'ace/mode/rust', label: 'Rust'},
  {id: 'ace/mode/sass', label: 'SASS'},
  {id: 'ace/mode/scad', label: 'SCAD'},
  {id: 'ace/mode/scala', label: 'Scala'},
  {id: 'ace/mode/scheme', label: 'Scheme'},
  {id: 'ace/mode/scss', label: 'SCSS'},
  {id: 'ace/mode/sh', label: 'SH'},
  {id: 'ace/mode/sjs', label: 'SJS'},
  {id: 'ace/mode/slim', label: 'Slim'},
  {id: 'ace/mode/smarty', label: 'Smarty'},
  {id: 'ace/mode/snippets', label: 'snippets'},
  {id: 'ace/mode/soy_template', label: 'Soy Template'},
  {id: 'ace/mode/space', label: 'Space'},
  {id: 'ace/mode/sql', label: 'SQL'},
  {id: 'ace/mode/sqlserver', label: 'SQLServer'},
  {id: 'ace/mode/stylus', label: 'Stylus'},
  {id: 'ace/mode/svg', label: 'SVG'},
  {id: 'ace/mode/swift', label: 'Swift'},
  {id: 'ace/mode/tcl', label: 'Tcl'},
  {id: 'ace/mode/terraform', label: 'Terraform'},
  {id: 'ace/mode/tex', label: 'Tex'},
  {id: 'ace/mode/text', label: 'Text'},
  {id: 'ace/mode/textile', label: 'Textile'},
  {id: 'ace/mode/toml', label: 'Toml'},
  {id: 'ace/mode/tsx', label: 'TSX'},
  {id: 'ace/mode/twig', label: 'Twig'},
  {id: 'ace/mode/typescript', label: 'Typescript'},
  {id: 'ace/mode/vala', label: 'Vala'},
  {id: 'ace/mode/vbscript', label: 'VBScript'},
  {id: 'ace/mode/velocity', label: 'Velocity'},
  {id: 'ace/mode/verilog', label: 'Verilog'},
  {id: 'ace/mode/vhdl', label: 'VHDL'},
  {id: 'ace/mode/visualforce', label: 'Visualforce'},
  {id: 'ace/mode/wollok', label: 'Wollok'},
  {id: 'ace/mode/xml', label: 'XML'},
  {id: 'ace/mode/xquery', label: 'XQuery'},
  {id: 'ace/mode/yaml', label: 'YAML'},
  {id: 'ace/mode/django', label: 'Django'},
];
export const THEMES = [
  {id: 'ace/theme/chrome', label: 'Chrome', light: true},
  {id: 'ace/theme/clouds', label: 'Clouds', light: true},
  {id: 'ace/theme/crimson_editor', label: 'Crimson Editor', light: true},
  {id: 'ace/theme/dawn', label: 'Dawn', light: true},
  {id: 'ace/theme/dreamweaver', label: 'Dreamweaver', light: true},
  {id: 'ace/theme/eclipse', label: 'Eclipse', light: true},
  {id: 'ace/theme/github', label: 'GitHub', light: true},
  {id: 'ace/theme/iplastic', label: 'IPlastic', light: true},
  {id: 'ace/theme/solarized_light', label: 'Solarized Light', light: true},
  {id: 'ace/theme/textmate', label: 'TextMate', light: true},
  {id: 'ace/theme/tomorrow', label: 'Tomorrow', light: true},
  {id: 'ace/theme/xcode', label: 'XCode', light: true},
  {id: 'ace/theme/kuroir', label: 'Kuroir', light: true},
  {id: 'ace/theme/katzenmilch', label: 'KatzenMilch', light: true},
  {id: 'ace/theme/sqlserver', label: 'SQL Server', light: true},
  {id: 'ace/theme/ambiance', label: 'Ambiance', light: false},
  {id: 'ace/theme/chaos', label: 'Chaos', light: false},
  {id: 'ace/theme/clouds_midnight', label: 'Clouds Midnight', light: false},
  {id: 'ace/theme/dracula', label: 'Dracula', light: false},
  {id: 'ace/theme/cobalt', label: 'Cobalt', light: false},
  {id: 'ace/theme/gruvbox', label: 'Gruvbox', light: false},
  {id: 'ace/theme/gob', label: 'Green on Black', light: false},
  {id: 'ace/theme/idle_fingers', label: 'idle Fingers', light: false},
  {id: 'ace/theme/kr_theme', label: 'krTheme', light: false},
  {id: 'ace/theme/merbivore', label: 'Merbivore', light: false},
  {id: 'ace/theme/merbivore_soft', label: 'Merbivore Soft', light: false},
  {id: 'ace/theme/mono_industrial', label: 'Mono Industrial', light: false},
  {id: 'ace/theme/monokai', label: 'Monokai', light: false},
  {id: 'ace/theme/pastel_on_dark', label: 'Pastel on dark', light: false},
  {id: 'ace/theme/solarized_dark', label: 'Solarized Dark', light: false},
  {id: 'ace/theme/terminal', label: 'Terminal', light: false},
  {id: 'ace/theme/tomorrow_night', label: 'Tomorrow Night', light: false},
  {id: 'ace/theme/tomorrow_night_blue', label: 'Tomorrow Night Blue', light: false},
  {id: 'ace/theme/tomorrow_night_bright', label: 'Tomorrow Night Bright', light: false},
  {id: 'ace/theme/tomorrow_night_eighties', label: 'Tomorrow Night 80s', light: false},
  {id: 'ace/theme/twilight', label: 'Twilight', light: false},
  {id: 'ace/theme/vibrant_ink', label: 'Vibrant Ink', light: false}
];
